export const initialState = {
  products: {
    data: [
      {
        id: 1,
        photo: 'https://i.postimg.cc/XNmDq8dh/Had-Bamboo-Street-Main-2048x2048.jpg',
        photo2: 'https://i.postimg.cc/mkqDN39L/Had-Bamboo-Street-Main-2.jpg',
        photo3: 'https://i.postimg.cc/Bb1s3r83/Had-Bamboo-Street-Main-3.jpg',
        title: 'HADEAN BAMBOO',
        price: '2001',
        text: 'Vivamus sapien nulla, porta sit amet est at, bibendum viverra massa. Vestibulum dignissim tincidunt velit vel laoreet. Curabitur ut enim odio. Praesent aliquet, risus id venenatis mollis, orci lacus ultrices dolor, vitae lacinia nisl odio sed neque. Sed laoreet sollicitudin dolor vel luctus. Ut elementum nec felis id scelerisque. Vivamus quis neque feugiat nulla tincidunt cursus. Phasellus nibh diam, ornare sed consectetur sit amet, lacinia quis nulla. Aliquam tellus ante, mattis at turpis vitae, blandit lobortis turpis.',
      },
      {
        id: 2,
        photo: 'https://i.postimg.cc/pT04sM9X/Had-Carbon-AT-Main-2048x2048.jpg',
        photo2: 'https://i.postimg.cc/yx9djgy0/Had-Carbon-AT-Main-2.jpg',
        photo3: 'https://i.postimg.cc/9QXmRNKd/Had-Carbon-AT-Main-3.jpg',
        title: 'HADEAN CARBON',
        price: '2002',
        text: 'Vivamus sapien nulla, porta sit amet est at, bibendum viverra massa. Vestibulum dignissim tincidunt velit vel laoreet. Curabitur ut enim odio. Praesent aliquet, risus id venenatis mollis, orci lacus ultrices dolor, vitae lacinia nisl odio sed neque. Sed laoreet sollicitudin dolor vel luctus. Ut elementum nec felis id scelerisque. Vivamus quis neque feugiat nulla tincidunt cursus. Phasellus nibh diam, ornare sed consectetur sit amet, lacinia quis nulla. Aliquam tellus ante, mattis at turpis vitae, blandit lobortis turpis.',
      },
      {
        id: 3,
        photo: 'https://i.postimg.cc/j5tZtPLS/Exway-Wave-1.jpg',
        photo2: 'https://i.postimg.cc/C5W8Lpms/Exway-Wave-2.jpg',
        photo3: 'https://i.postimg.cc/TYDmNh37/Exway-Wave-3.jpg',
        title: 'EXWAY WAVE',
        price: '2003',
        text: 'Vivamus sapien nulla, porta sit amet est at, bibendum viverra massa. Vestibulum dignissim tincidunt velit vel laoreet. Curabitur ut enim odio. Praesent aliquet, risus id venenatis mollis, orci lacus ultrices dolor, vitae lacinia nisl odio sed neque. Sed laoreet sollicitudin dolor vel luctus. Ut elementum nec felis id scelerisque. Vivamus quis neque feugiat nulla tincidunt cursus. Phasellus nibh diam, ornare sed consectetur sit amet, lacinia quis nulla. Aliquam tellus ante, mattis at turpis vitae, blandit lobortis turpis.',
      },
      {
        id: 4,
        photo: 'https://i.postimg.cc/7hcRHhFt/Exway-x1-max-3.png',
        photo2: 'https://i.postimg.cc/RZTjfSKh/Exway-x1-max-4.png',
        photo3: 'https://i.postimg.cc/HkTNTqRg/Exway-x1-max-5.png',
        title: 'EXWAY X1 MAX',
        price: '2004',
        text: 'Vivamus sapien nulla, porta sit amet est at, bibendum viverra massa. Vestibulum dignissim tincidunt velit vel laoreet. Curabitur ut enim odio. Praesent aliquet, risus id venenatis mollis, orci lacus ultrices dolor, vitae lacinia nisl odio sed neque. Sed laoreet sollicitudin dolor vel luctus. Ut elementum nec felis id scelerisque. Vivamus quis neque feugiat nulla tincidunt cursus. Phasellus nibh diam, ornare sed consectetur sit amet, lacinia quis nulla. Aliquam tellus ante, mattis at turpis vitae, blandit lobortis turpis.',
      },
      {
        id: 5,
        photo: 'https://i.postimg.cc/4NP5QmLD/Exway-Flex-1.png',
        photo2: 'https://i.postimg.cc/qR2chR6Z/Exway-Flex-2.png',
        photo3: 'https://i.postimg.cc/Hsk5H3zN/Exway-Flex-3.png',
        title: 'EXWAY FLEX',
        price: '2005',
        text: 'Vivamus sapien nulla, porta sit amet est at, bibendum viverra massa. Vestibulum dignissim tincidunt velit vel laoreet. Curabitur ut enim odio. Praesent aliquet, risus id venenatis mollis, orci lacus ultrices dolor, vitae lacinia nisl odio sed neque. Sed laoreet sollicitudin dolor vel luctus. Ut elementum nec felis id scelerisque. Vivamus quis neque feugiat nulla tincidunt cursus. Phasellus nibh diam, ornare sed consectetur sit amet, lacinia quis nulla. Aliquam tellus ante, mattis at turpis vitae, blandit lobortis turpis.',
      },
      {
        id: 6,
        photo: 'https://i.postimg.cc/zfKHpQDy/Exway-Atlas-1.png',
        photo2: 'https://i.postimg.cc/rsBLhfwp/Exway-Atlas-2.png',
        photo3: 'https://i.postimg.cc/63D9SWHw/Exway-Atlas-3.png',
        title: 'EXWAY ATLAS',
        price: '2006',
        text: 'Vivamus sapien nulla, porta sit amet est at, bibendum viverra massa. Vestibulum dignissim tincidunt velit vel laoreet. Curabitur ut enim odio. Praesent aliquet, risus id venenatis mollis, orci lacus ultrices dolor, vitae lacinia nisl odio sed neque. Sed laoreet sollicitudin dolor vel luctus. Ut elementum nec felis id scelerisque. Vivamus quis neque feugiat nulla tincidunt cursus. Phasellus nibh diam, ornare sed consectetur sit amet, lacinia quis nulla. Aliquam tellus ante, mattis at turpis vitae, blandit lobortis turpis.',
      },
    ],

    loading: {
      active: false,
      error: false,
    },
  },
};
